version: '1.0.{build}'
#assembly_info:
#  patch: true
#  file: '**\*.csproj'
dotnet_csproj:
  patch: true
  file: 'TestingLab2Core.csproj'
  version: 5.0.3
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: TestingLab2Core.sln
before_build:
  - nuget restore